### ISSUE TITLE
Fix all intermediary BigNumber to number conversions to potential conversion panics

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#29]
Example error on ethTru pool
```
Error: while converting number to string, invalid number value '1.1699306e-11', should be a number matching (^-?[0-9.]+).
    at numberToString (/Users/admin/Documents/j121/avalidator/node_modules/ethjs-unit/lib/index.js:61:13)
    at Object.toWei (/Users/admin/Documents/j121/avalidator/node_modules/ethjs-unit/lib/index.js:114:15)
    at Object.toWei (/Users/admin/Documents/j121/avalidator/node_modules/web3-utils/lib/index.js:250:75)
    at /Users/admin/Documents/j121/avalidator/oracle/submitter/utils/setBulkRewardRate.js:23:81
    at Array.map (<anonymous>)
    at exports.setBulkRewardRate (/Users/admin/Documents/j121/avalidator/oracle/submitter/utils/setBulkRewardRate.js:23:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async feedRewardRates (/Users/admin/Documents/j121/avalidator/oracle/submitter/feedRewardRates/index.js:84:13)
    at async feed (/Users/admin/Documents/j121/avalidator/oracle/submitter/index.js:7:5)
```

**Comment by Abhishekkochar** [comment]
Issue fixed. 
`dailyRewardRates = dailyRewardRates.map(rate => web3.utils.toHex(web3.utils.toWei(`${parseInt(rate * 1e18)/**_1e18_**}`, 'ether')))`

resulting in too many decimals.

**Comment by gophereth** [comment]
You can check further comments on the desired goal of this ticket here
https://github.com/ArableProtocol/arablevalidator/pull/34
