### ISSUE TITLE
Polygon chain data not fetching

### ISSUE THREAD

**Issue by Abhishekkochar** [ArableProtocol/arablevalidator#31]
When running oracle/index script. Unable to fetch data from polygon chain. 

Console: 
`  "poly": {
                "polygonData": {}
        },`

`TypeError: Cannot read properties of undefined (reading 'rewardRate')
    at convertToFormalRewardRates (/mnt/c/pr0/arablevalidator/oracle/submitter/feedRewardRates/index.js:32:62)
    at feedRewardRates (/mnt/c/pr0/arablevalidator/oracle/submitter/feedRewardRates/index.js:79:33)
    at feed (/mnt/c/pr0/arablevalidator/oracle/submitter/index.js:7:11)
    at Task._execution (/mnt/c/pr0/arablevalidator/oracle/index.js:11:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by Abhishekkochar** [comment]
Eth/usdc pool wasn't able to import rpc URL. Pass the original value in the file at this stage.

**Comment by gophereth** [comment]
I was able to get polygon data by configuring below on env
MATIC_RPC="https://polygon-mainnet.g.alchemy.com/v2/KdZl6-6vZ3PkKc-MHMiLPjt1zLbUuKfS"
